// This file was auto-generated by the D2DEZ asset manager from:
// "#PATH#"
//plzio
#pragma once
#include <Windows.h>

constexpr int #NAME#_Width = #WIDTH#;
constexpr int #NAME#_Height = #HEIGHT#;
constexpr BYTE #NAME#_Buffer[] = #BUFFER#;

constexpr Asset #NAME# = { #NAME#_Width, #NAME#_Height, #NAME#_Buffer };